<a href="https://colab.research.google.com/github/Allan-Robert/Aulas_Python_20252/blob/main/Numpy_e_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Falando do NumPy
O NumPy (Numerical Python) é a biblioteca fundamental para a computação científica em Python.

Características:
* Objeto ndarray (N-dimensional Array): É a estrutura básica do NumPy. É um grade (array) homogêneo e multidimensional mais eficiente em termos de memória e velocidade do que as listas nativas do Python para operações numéricas.
* Velocidade: As operações no NumPy são implementadas em C, o que as torna mais rápidas do que operações em Python puro, em especialmente para grande volume de dados.
* Funções Matemáticas Abrangentes:Oferece uma vasta coleção de funções para operações matemáticas elementares como trigonometria, logaritmos, etc. Ferramentas com métodos de Álgebra linear, além de estatísticas descritivas e distribuições de probabilidade.

In [2]:
###
import numpy as np
l=[2,1,4,5,6,9,12,22]
### Funções estatísticas e matemáticas
np.sin(l)
np.cos(l)
np.max(l)
np.mean(l)
np.std(l)
np.var(l)
np.median(l)

am=np.random.normal(10,2,20)
type(am)

numpy.ndarray

In [3]:
## indexação em numpy é semelhante as lista
am[4:]
am[-1]

np.float64(9.124722797298828)

## Pandas

O Pandas é a biblioteca mais utilizada em Python para manipulação e análise de dados. Ela oferece um estruturas de dados com uma gama de funções para dados como: leitura, limpeza, filtragem, agrupamento, agregação, transformações e descritivas.

Estruturas Chaves:

*Series (Série): Um array rotulado, unidimensional, similar a uma coluna em uma planilha ou um vetor (construído sobre o NumPy).

*DataFrame (Tabela de Dados): A estrutura principal. É uma tabela bidimensional, onde cada coluna é um objeto Series e todas compartilham o mesmo índice (rótulo) de linha.

In [15]:
import pandas as pd

aluno=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Alunos.csv",encoding='latin1',sep=';')
aluno.head(2)

   Curso  Sexo  Idade  Proveniência  Nota1  Nota2  Frequência
0      1     1     32             1      7      8        0.75
1      1     2     23             2      4      7        0.85

In [27]:
aluno.info() # informações gerais importantes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Curso         58 non-null     object
 1   Sexo          58 non-null     object
 2   Idade         58 non-null     int64
 3   Proveniência  58 non-null     category
 4   Nota1         58 non-null     int64
 5   Nota2         58 non-null     int64
 6   Frequência    58 non-null     float64
dtypes: category(1), float64(1), int64(3), object(2)
memory usage: 3.0+ KB

In [22]:
## Como fazer referência as colunas
aluno['Curso'] # referencia direta de uma coluna
aluno[['Curso','Sexo']]# mais de uma coluna
aluno.iloc[:,[1,3,5]] # citar por numeração a coluna (Quando se tem muitas colunas)

Sexo            2.0
Proveniência    2.0
Nota2           7.0
Name: 1, dtype: float64

In [23]:
## 1 Estatística e 2 Ciências Atuariais
def mcurso(num):
  if num==1:
    return 'Estatística'
  else: return 'Ciências Atuariais'

aluno['Curso']=aluno['Curso'].apply(mcurso)
aluno.head(3)

         Curso  Sexo  Idade  Proveniência  Nota1  Nota2  Frequência
0  Estatística     1     32             1      7      8        0.75
1  Estatística     2     23             2      4      7        0.85
2  Estatística     1     21             1      7      3        1.00

In [25]:
## função lambda
aluno['Sexo']=aluno['Sexo'].apply(lambda x: 'Masculino' if x==1 else 'Feminino')
aluno.head(3)

         Curso       Sexo  Idade  Proveniência  Nota1  Nota2  Frequência
0  Estatística  Masculino     32             1      7      8        0.75
1  Estatística   Feminino     23             2      4      7        0.85
2  Estatística  Masculino     21             1      7      3        1.00

In [26]:
## uso do cut 1 publica 2 particular 3 federal
intervalos=[0,1.5,2.5,3.5]
nomes=['Pública','Particular','Federal']
aluno['Proveniência']=pd.cut(aluno['Proveniência'],bins=intervalos,labels=nomes)
aluno.head(3)

         Curso       Sexo  Idade Proveniência  Nota1  Nota2  Frequência
0  Estatística  Masculino     32      Pública      7      8        0.75
1  Estatística   Feminino     23   Particular      4      7        0.85
2  Estatística  Masculino     21      Pública      7      3        1.00

In [29]:
# criar uma coluna nova
aluno['Média']=round((aluno['Nota1']+aluno['Nota2'])/2,2)
aluno.head(3)

         Curso       Sexo  Idade Proveniência  Nota1  Nota2  Frequência  Média
0  Estatística  Masculino     32      Pública      7      8        0.75    7.5
1  Estatística   Feminino     23   Particular      4      7        0.85    5.5
2  Estatística  Masculino     21      Pública      7      3        1.00    5.0

In [30]:
aluno.to_csv('/content/drive/MyDrive/Colab Notebooks/Alunos_corrigido.csv',encoding='utf-8',header=True,index=False)